### PR TITLE
refactor: improved auth logic for firebase

### PR DESCRIPTION
**Pull request by Mvrs**

### CODE REVIEW

**Comment by Mvrs** [comment]
This is not ready for merge yet but hopefully, someone can test these changes. @hanguyen0

**Comment by hanguyen0** [comment]
I will, thanks Mars :)

**Review by hanguyen0 — APPROVED** [review]
I tested the auth logic, it's a lot smoother than before

**Comment by Mvrs** [comment]
> I tested the auth logic, it's a lot smoother than before 

Thanks @hanguyen0 still room for improvement once we get the UI/UX design 🙃

**Pull request closed without merging**
